on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: mbalestrini/hello-world-docker-action@v2
        with:
          who-to-greet: 'Pedro'
      - name: upload render output
        uses: actions/upload-artifact@v2
        with:
                name: render_out.png
                path: /tmp/0001.png

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
